### PR TITLE
fix: address filter and quotation to for prospect

### LINKED ISSUE #41015: Quotation address does not cater for Prospect
### Information about bug

When a quote is made against a Prospect, the customer addresses offered are empty due to a bug in this line:

https://github.com/frappe/erpnext/blob/760e341cd07b1cebe6c4c8d05d8e77f5a9da89c7/erpnext/selling/doctype/quotation/quotation.js#L100

### Module

selling

### Version

v16 develop

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by Nihantra-Patel**
**Version 15**

fixes: #41015

**Before:** 

- When choosing "quotation_to" as a customer, the customer displays correctly. Similarly, when selecting "quotation_to" as the lead, the lead displays correctly. However, when "quotation_to" is set as a prospect, the lead list is shown instead. Moreover, when initially selecting "quotation_to" as a customer and then changing it to prospect, it displays properly.

- In the case where "quotation_to" is set as a prospect, the address does not appear, and the address filter does not correspond to the prospect; instead, it shows the lead address.

https://github.com/frappe/erpnext/assets/141945075/f94d506f-dea3-481b-a9d1-a77f4e9864d9

<br>

**After:**

- fix the issue, so please check the video.

https://github.com/frappe/erpnext/assets/141945075/b0796331-48e2-430e-ae9a-fe379faa11de

### CODE REVIEW

File: erpnext/selling/doctype/quotation/quotation.js [hunk 1]
```diff
@@ -94,10 +96,18 @@ erpnext.selling.QuotationController = class QuotationController extends erpnext.
...
+		} else if (doc.quotation_to == "Lead") {
+			doctype = "Lead";
+		} else if (doc.quotation_to == "Prospect") {
+			doctype = "Prospect";
+		}
 		frappe.dynamic_link = {
 			doc: this.frm.doc,
 			fieldname: "party_name",
-			doctype: doc.quotation_to == "Customer" ? "Customer" : "Lead",
+			doctype: doctype,
```
Comment (casesolved-co-uk) [inline erpnext/selling/doctype/quotation/quotation.js]: Why not just do:

`doctype: doc.quotation_to`?

Futureproof.

**Comment by casesolved-co-uk** [comment]
@Nihantra-Patel nice work

File: erpnext/selling/doctype/quotation/quotation.js (hunk 1 above)
Comment (Nihantra-Patel) [reply erpnext/selling/doctype/quotation/quotation.js]: Code snippet uses a series of if and else if statements to explicitly set the variable doctype based on the value of doc.quotation_to. This approach clearly handles each case ("Customer," "Lead," "Prospect") individually, and it's easy to read and modify.

The suggested alternative in your question (doctype: doc.quotation_to == "Customer" ? "Customer" : "Lead") is not equivalent because it only checks if doc.quotation_to is "Customer" and incorrectly defaults to "Lead" without verifying if it should indeed be "Lead." This misses cases like "Prospect" and any other potential values.

Using a ternary operator for this purpose can lead to errors or reduced clarity, especially when multiple conditions are involved. The original method using if-else statements is more appropriate here for clarity and accuracy.

Comment (casesolved-co-uk) [reply erpnext/selling/doctype/quotation/quotation.js]: No you misunderstand me. There is no need to do an if-else or ternary operator, because `quotation_to` can only be the values in the Select field anyway.

Comment (Nihantra-Patel) [reply erpnext/selling/doctype/quotation/quotation.js]: Try it.

Comment (casesolved-co-uk) [reply erpnext/selling/doctype/quotation/quotation.js]: Okay so a filtered Link field rather than Select, but same effect.
I don't need to try it, it can only be these values:
Screen Shot 2024-04-30 at 18 20 35

Comment (casesolved-co-uk) [reply erpnext/selling/doctype/quotation/quotation.js]:
```javascript
                        frm.set_query("quotation_to", function () {
                                return {
                                        filters: {
                                                name: ["in", ["Customer", "Lead", "Prospect"]],
                                        },
                                };
                        });
```

**Review by ruthra-kumar — APPROVED** [review]
