### PR TITLE
fix: prevent employees from selecting themselves in "Reports To" dropdown (closes #3183)

### LINKED ISSUE #3183: Translate
captura de pantalla 2015-04-28 a las 20 34 41
There are some words that are not found to translate like the image.

### LINKED ISSUE #49142: Employee allowed to report to self
### Information about bug

If you create an employee and click the space for "Report To", it shows the same employee ID as well as an option in the drop down. 

Image

### Module

HR

### Version

ERPNext version - v15.62.0
Frappe HR version - v15.45.3

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Anjalii-Patel**
This PR addresses [#3183](https://github.com/frappe/erpnext/issues/49142) where an employee could see and select their own Employee ID in the "Reports To" field dropdown while creating or editing their profile.

Changes made:

Added a client-side filter to exclude the current employee from the "Reports To" field query.

Ensures that the dropdown only lists other employees, preventing self-report assignments before save-time validation.

Why this matters:
Although server-side validation already prevents saving an employee who reports to themselves, showing the same employee in the dropdown is confusing to users and could cause unnecessary form errors. This PR improves user experience by removing the invalid option upfront.

Testing done:

Created a new employee and verified the "Reports To" dropdown does not include the same Employee ID.

Edited an existing employee and confirmed no self-reference appears.

## Summary by CodeRabbit

* **Bug Fixes**
  * "Reports To" picker now only shows active employees and excludes the current employee to prevent self-reporting.
  * Company-level restriction is still noted but not enforced, so company scoping of the picker remains unchanged.

fixes #49142

### CODE REVIEW

File: erpnext/setup/doctype/employee/employee.js [hunk 1]
```diff
@@ -11,13 +11,23 @@ erpnext.setup.EmployeeController = class EmployeeController extends frappe.ui.fo
...
+    // exclude this employee by name (and doc.employee if present)
+    const exclude = [doc.name, doc.employee].filter(Boolean);
+    if (exclude.length) {
+        filters.push(["name", "not in", exclude]);
+    }
+    return {
+        query: "erpnext.controllers.queries.employee_query",
+        filters
+    };
+};
```
Comment (asmitahase) [inline erpnext/setup/doctype/employee/employee.js]: Your original code would have sufficed, this is not required, think of a multilevel company structure where head of a child company reports to someone from the parent company. Just remove the comment.

**Review by asmitahase — CHANGES_REQUESTED** [review]

**Comment by Anjalii-Patel** [comment]
@asmitahase I've removed the company scoping comment as suggested. Let me know if anything else needs updating. Thanks!

**Comment by asmitahase** [comment]
Also, setup pre-commit for linting, you'll find more in PR guidelines,
https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#linting

And make sure your commits follow the semantics
https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#pull-request-titles-and-commit-messages

File: erpnext/setup/doctype/employee/employee.js [hunk 2]
```diff
@@ -11,7 +11,13 @@ erpnext.setup.EmployeeController = class EmployeeController extends frappe.ui.fo
 			};
 		};
 		this.frm.fields_dict.reports_to.get_query = function (doc, cdt, cdn) {
-			return { query: "erpnext.controllers.queries.employee_query" };
+			// return { query: "erpnext.controllers.queries.employee_query" };
```
Comment (asmitahase) [inline erpnext/setup/doctype/employee/employee.js]: By remove the comment I meant this one. And the code in this commit is enough. Restricting employee records belonging to a company isn't required. You can revert all commits after this one

Comment (asmitahase) [inline erpnext/setup/doctype/employee/employee.js]: By remove the comment I meant L14. And the code in this commit is enough. Restricting employee records belonging to a company isn't required. You can revert all commits after this one

**Review by asmitahase — CHANGES_REQUESTED** [review]

File: erpnext/setup/doctype/employee/employee.js (hunk 2 above)
Comment (asmitahase) [reply erpnext/setup/doctype/employee/employee.js]: or better yet, reset them

File: erpnext/setup/doctype/employee/employee.js [hunk 3]
```diff
@@ -11,7 +11,13 @@ erpnext.setup.EmployeeController = class EmployeeController extends frappe.ui.fo
...
+			return {
+				filters: [
```
Comment (asmitahase) [inline erpnext/setup/doctype/employee/employee.js:16]: Missed adding query

**Review by asmitahase — CHANGES_REQUESTED** [review]

**Review by asmitahase — APPROVED** [review]

**Comment by mihir-kandoi** [comment]
@asmitahase can we merge this?
