### PR TITLE
fix: Select both account number and company in the account form

### LINKED ISSUE #41695: Unresolved #29048 – Cannot select company when adding a new account in Chart Of Accounts
### Information about bug

See: https://github.com/frappe/erpnext/issues/29048

In a multi-company setup, when adding a new account from the list view, the **Company** field is grayed out (pre-filled with the default company). Adding via Tree view is still possible:

image

### Module

accounts

### Version

```
erpnext 15.19.0
erpnextswiss 1.23.2
frappe 15.20.0
hrms 15.16.0
payments 0.0.1
```

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by Nihantra-Patel**
fixes: #41695

**Before:**

image

**After:**

- Both account number and company should be selected in the account form. This is important because if the user wants to change the company, the account form needs to have a way to set the company. Additionally, each user selects by going to the account doctype instead of adding the account in the chart of accounts tree, so in this case, users have the right to select the company.

image

### CODE REVIEW

File: erpnext/accounts/doctype/account/account.js [hunk 1]
```diff
@@ -22,9 +22,6 @@ frappe.ui.form.on("Account", {
 		// hide fields if group
 		frm.toggle_display(["tax_rate"], cint(frm.doc.is_group) == 0);
 
-		// disable fields
-		frm.toggle_enable(["is_group", "company"], false);
```
Comment (nabinhait) [inline erpnext/accounts/doctype/account/account.js:26]: These fields cannot be editable after save.

frm.toggle_enable(["is_group", "company", "account_number"], frm.is_new());

**Review by nabinhait — CHANGES_REQUESTED** [review]

**Review by nabinhait — APPROVED** [review]
