### PR TITLE
[fix] Payment Entry - draft sales invoices should not be selectable

### LINKED ISSUE #8044: Payment Entry - Draft Sales Invoices should not be selectable
screen shot 2017-03-16 at 3 19 44 pm

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
Fixed #8044

### CODE REVIEW

File: erpnext/accounts/doctype/payment_entry/payment_entry.js [hunk 1]
```diff
@@ -78,6 +78,19 @@ frappe.ui.form.on('Payment Entry', {
 				filters: { "name": ["in", doctypes] }
 			};
 		});
+
+		frm.set_query("reference_name", "references", function(doc, cdt, cdn) {
+			child = locals[cdt][cdn];
+			filters = { "docstatus": 1 };
```
Comment (nabinhait) [inline erpnext/accounts/doctype/payment_entry/payment_entry.js]: Also add company filter

**Review by nabinhait — CHANGES_REQUESTED** [review]

File: erpnext/accounts/doctype/payment_entry/payment_entry.js (hunk 1 above)
Comment (rohitwaghchaure) [inline erpnext/accounts/doctype/payment_entry/payment_entry.js]: Fixed
