### PR TITLE
fix: POS print receipt

### LINKED ISSUE #24875: Unable to print receipt in POS
Hi there, I am unable to print receipt in POS page. when ever i click PRINT RECEIPT button it is giving below js error

Uncaught TypeError: Cannot set property 'lang_code' of undefined.

I explored the files and found that this error is coming from 
https://github.com/frappe/erpnext/blob/e196be4d8ab3b80867f8b0da19923483bdcfeb86/erpnext/selling/page/point_of_sale/pos_past_order_summary.js#L69

I am using erpnext v13 develop branch

## Steps to reproduce the issue

1. Create a pos invoice in POS page
2. Click print receipt or press Ctrl+p shortcut

### PR DESCRIPTION
**Pull request by prssanna**
Fixes broken print in POS.
Depends on https://github.com/frappe/frappe/pull/12591

Fixes: https://github.com/frappe/erpnext/issues/24875

### CODE REVIEW

File: erpnext/selling/page/point_of_sale/pos_past_order_summary.js [hunk 1]
```diff
@@ -193,9 +193,13 @@ erpnext.PointOfSale.PastOrderSummary = class {
...
-			frm.doc = this.doc;
-			frm.print_preview.lang_code = frm.doc.language;
-			frm.print_preview.printit(true);
+			frappe.utils.print(
+				frm.doctype,
+				frm.docname,
+				frm.pos_print_format,
+				frm.doc.letter_head,
+				frm.doc.language || frappe.boot.lang
+			)
```
Comment (nextchamp-saqib) [inline erpnext/selling/page/point_of_sale/pos_past_order_summary.js]:
```suggestion
			);
```

**Comment by nextchamp-saqib** [comment]
@prssanna  This works! On line 69 the same code needs to be added.
