### PR TITLE
Payroll Entry (#11936)

### LINKED ISSUE #11936: Payroll Entry
Provide Payroll Entry status in the indicator

1. Salary Slip in Draft
2. Salary Slip Submitted
3. Bank / Payment Entry pending
4. Bank Entry Completed, or just Payroll Completed

In the Toolbar button, make next step button as Primary, if possible. Currently, it doesn't give a starting point.

screen shot 2017-12-11 at 6 06 15 pm

If Salary Slip submission fails, then validation first indicates about email not being sent, and then shows error message related to the failure of the Salary Slip submission. The cause of the Failure should be shown up in the order. Maybe email related validation should be shown after Salary Slip is submitted Successfully.

screen shot 2017-12-11 at 6 07 48 pm

### PR DESCRIPTION
**Pull request by tundebabzy**
Fixes #11936 

peek 2017-12-12 22-00

### CODE REVIEW

File: erpnext/hr/doctype/payroll_entry/payroll_entry.js [hunk 1]
```diff
@@ -10,24 +10,73 @@ frappe.ui.form.on('Payroll Entry', {
...
 
+	add_bank_entry_button: function(frm) {
+		frappe.call({
+			method: 'erpnext.hr.doctype.payroll_entry.payroll_entry.payroll_entry_has_bank_entries',
+			args: {
+				'name': frm.doc.name
+			},
+			callback: function(r) {
+				if (r.message && !r.message.submitted) {
+					frm.add_custom_button("Make Bank Entry",
```
Comment (shreyashah115) [inline erpnext/hr/doctype/payroll_entry/payroll_entry.js]: Shouldn't it be only 'Bank Entry' as its already inside the Make button?
