### PR TITLE
fix: Company currency label is not displayed in Landed Cost Voucher doctype for the field Total Vendor Invoices Cost

### LINKED ISSUE #49288: Company currency label is not displayed in Landed Cost Voucher doctype for the field `Total Vendor Invoices Cost`
### Information about bug

In Landed Cost Voucher DocType, 
- Field `Total Vendor Invoices Cost` is not displaying company currency label
- And in field it showing global default currency symbol

Image

### Module

stock

### Version

Frappe Framework: v15.x.x-develop (939fd9e) (develop) 
ERPNext: develop

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell

```

### PR DESCRIPTION
**Pull request by anwarpatelnoori**
Closes #49288

> Please provide enough information so that others can review your pull request:
- Currently, company currency label is not displayed in Landed Cost Voucher doctype for the field `Total Vendor Invoices Cost`
image

> Explain the **details** for making this change. What existing problem does the pull request solve?
- To show current currency label for the `Total Vendor Invoices Cost` in Landed Cost Voucher doctype

> Screenshots/GIFs
image

**The same can be fixed in version-15**

### CODE REVIEW

**Comment by anwarpatelnoori** [comment]
@mihir-kandoi @rohitwaghchaure @ruthra-kumar please review

File: erpnext/stock/doctype/landed_cost_voucher/landed_cost_voucher.js [hunk 1]
```diff
@@ -63,6 +63,7 @@ erpnext.stock.LandedCostVoucher = class LandedCostVoucher extends erpnext.stock.
 		if (this.frm.doc.company) {
 			let company_currency = frappe.get_doc(":Company", this.frm.doc.company).default_currency;
 			this.frm.set_currency_labels(["total_taxes_and_charges"], company_currency);
+			this.frm.set_currency_labels(["total_vendor_invoices_cost"], company_currency);
```
Comment (mihir-kandoi) [inline erpnext/stock/doctype/landed_cost_voucher/landed_cost_voucher.js]:
```suggestion
			this.frm.set_currency_labels(["total_taxes_and_charges", "total_vendor_invoices_cost"], company_currency);
```

**Review by mihir-kandoi — CHANGES_REQUESTED** [review]
line is redundant, fieldname can simply be added to the `set_currency_labels` call above

File: erpnext/stock/doctype/landed_cost_voucher/landed_cost_voucher.js (hunk 1 above)
Comment (anwarpatelnoori) [reply erpnext/stock/doctype/landed_cost_voucher/landed_cost_voucher.js]: @mihir-kandoi , I have refactored and it is displaying correct 
image

**Review by mihir-kandoi — APPROVED** [review]

**Comment by anwarpatelnoori** [comment]
@mihir-kandoi
