### PR TITLE
fix: fiscal year error on new setup and continuous request

### LINKED ISSUE #47187: Annoying fiscal year error on new setup
Image

Steps:
1. Create a new site
2. Log in

Fix for the date aside, this API call on every load needs to go!

### PR DESCRIPTION
**Pull request by diptanilsaha**
Fixed the continuous API call on every reload. Also, added a fix to fetch the current fiscal year in boot based on the User's default Company.

### CODE REVIEW

File: erpnext/public/js/utils.js [hunk 1]
```diff
@@ -444,7 +445,7 @@ $.extend(erpnext.utils, {
 		) {
 			if (with_dates) fiscal_year = frappe.boot.current_fiscal_year;
 			else fiscal_year = frappe.boot.current_fiscal_year[0];
-		} else {
+		} else if (today != date) {
```
Comment (ankush) [inline erpnext/public/js/utils.js:448]: Why is it even reaching here? shouldn't it get resolved using `boot` in most common cases?

Comment (ankush) [reply erpnext/public/js/utils.js:448]: Can you update description to describe why this change is correct. To me this seems like it will just avoid fiscal year fetching if date==today but it should at least return something???

Comment (diptanilsaha) [reply erpnext/public/js/utils.js:448]: > Why is it even reaching here? shouldn't it get resolved using `boot` in most common cases?

In the common case, it should get resolved at `boot`. I kept that API call in case someone wants to use the `get_fiscal_year` to fetch the fiscal year for a date.

Comment (diptanilsaha) [reply erpnext/public/js/utils.js:448]: > Can you update description to describe why this change is correct. To me this seems like it will just avoid fiscal year fetching if date==today but it should at least return something???

It will bring back the same annoying fiscal year error in case the Fiscal Year is not set.

Comment (ankush) [reply erpnext/public/js/utils.js:448]: But, it should be handled here? 

image

cc @deepeshgarg007 (since you originally added this)

Comment (nabinhait) [reply erpnext/public/js/utils.js:448]: If the date doesn't belong to the current fiscal year, then we need a server call.

**Review by nabinhait — APPROVED** [review]
