### PR TITLE
fix: skip timesheet on return time

### LINKED ISSUE #37583: Credit Note Create Issue against Sales Invoice (Timesheet Link)
### Information about bug

we are not able to create credit note to customer against sales invoice , which sales invoice created against timesheet.
below popup show

image

when we go on timesheet to cancelled so system don't allow, system say 1st cancelled Sales Invoice but how we can create credit note to customer??
image

### Module

accounts

### Version

ERPNext: v14.38.0 (HEAD)
Frappe Framework: v14.48.1 (HEAD)
India Compliance: v14.16.2 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

### LINKED ISSUE #40192: This bug is related to credit note. Pls checking adding Timesheet against customer and project > fetch timesheet in sales invoice > create credit note against same invoice. same issue in V15 also
@Nihantra-you are doing wrong testing. This bug is related to credit note. Pls checking adding Timesheet against customer and project > fetch timesheet in sales invoice > create credit note against same invoice. same issue in V15 also
image

_Originally posted by @RJMHASKE in https://github.com/frappe/erpnext/issues/37583#issuecomment-1970666227_

### PR DESCRIPTION
**Pull request by Nihantra-Patel**
Version 15 and 14

fixes: #37583 / #40192

**Before:** 

- We can't make a credit note for a customer based on a sales invoice that was created from a timesheet. and other issue return time. please check the video.

https://github.com/frappe/erpnext/assets/141945075/395e5a4a-d787-44b3-8eb3-cc4476281287

<br>

**After:**

https://github.com/frappe/erpnext/assets/141945075/be61e9af-bc08-4d21-b2d7-e268247596ab

<br>

Thank You!

### CODE REVIEW

File: erpnext/accounts/doctype/sales_invoice/sales_invoice.js [hunk 1]
```diff
@@ -486,7 +486,7 @@ erpnext.accounts.SalesInvoiceController = class SalesInvoiceController extends e
 	currency() {
 		var me = this;
 		super.currency();
-		if (this.frm.doc.timesheets) {
+		if (!this.frm.doc.is_return && this.frm.doc.timesheets) {
```
Comment (barredterra) [inline erpnext/accounts/doctype/sales_invoice/sales_invoice.js]: The error here would better be solved by disabling the "No Copy" attribute of the _Timesheet Detail_ column of **Sales Invoice Timesheet**.

Comment (Nihantra-Patel) [reply erpnext/accounts/doctype/sales_invoice/sales_invoice.js]: Hi @barredterra,

I already had an idea 😅  and I set "no copy" then both problems were solved but I was a bit confused 🤔 but you are right. Now I simply add "no copy". Thank you very much for looking at and reviewing PR. 😄 

I will update the PR.

**Comment by ruthra-kumar** [comment]
@mergify backport version-15-hotfix

**Comment by ruthra-kumar** [comment]
v15 backport: https://github.com/frappe/erpnext/pull/41823
