### PR TITLE
fix: pos payment using non-default mode of payment

### LINKED ISSUE #41108: [Bug] - POS - Point of Sale breaks when using "Non-default Mode of Payment"
### Information about bug

POS breaks when using non default mode of payment. I think it is related to **"Update Account Number / Name"** feature under "Accounts". 

**After troubleshooting I figured that: Bug is caused by using Special characters like **\ ; -- # % & ()** as "Mode of Payment" name filled** It gets fixed after utilizing regular letters

### **Visuals**
Non Default "Mode of Payment":
(Does not work): Does not let me enter the ammount
image
image
image

Default "Mode of Payment": Cash
(Works Fine)
image
image

### Module

stock, selling

### Version

ERPNext: v15.20.2

Frappe Framework: v15.21.0

Frappe HR: v15.17.0

Payments: v0.0.1

Webshop: v0.0.1

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by diptanilsaha**
image

fixes: #41108

### CODE REVIEW

File: erpnext/selling/page/point_of_sale/pos_payment.js [hunk 1]
```diff
@@ -235,7 +235,11 @@ erpnext.PointOfSale.Payment = class {
 		frappe.ui.form.on("Sales Invoice Payment", "amount", (frm, cdt, cdn) => {
 			// for setting correct amount after loyalty points are redeemed
 			const default_mop = locals[cdt][cdn];
-			const mode = default_mop.mode_of_payment.replace(/ +/g, "_").toLowerCase();
+			const mode = default_mop.mode_of_payment
```
Comment (nabinhait) [inline erpnext/selling/page/point_of_sale/pos_payment.js]: create a function

**Review by nabinhait — CHANGES_REQUESTED** [review]

File: erpnext/selling/page/point_of_sale/pos_payment.js [hunk 2]
```diff
@@ -612,4 +612,12 @@ erpnext.PointOfSale.Payment = class {
 	toggle_component(show) {
 		show ? this.$component.css("display", "flex") : this.$component.css("display", "none");
 	}
+
+	mode_of_payment_to_class_name(mode_of_payment) {
```
Comment (nabinhait) [inline erpnext/selling/page/point_of_sale/pos_payment.js]: This is not a good function name, maybe it should be `sanitize_mode_of_payment`

**Review by nabinhait — CHANGES_REQUESTED** [review]

**Review by nabinhait — APPROVED** [review]
