### PR TITLE
fix: PO/PINV -  Check if doctype has company_address field before setting the value

### LINKED ISSUE #27419: "Field company_address not found." Error when creating a new Purchase Order or Purchase Invoice
## Description of the issue
Upon creating a new Purchase Order, or a Purchase Invoice, an error pops up indicating that the field "company_address" is not found. This happened after upgrading to the latest release.

## Context information (for bug reports)
 I do suspect this new problem as come from changes made to fix issue #27217: https://github.com/frappe/erpnext/pull/27217

## Steps to reproduce the issue

1. Create a new Purchase Order, or Create a new Purchase Invoice

### Observed result
Error modal with the content: "Field company_address not found."

### Expected result
No error, and the page loads as usual.

ERPNext: v13.10.2 (version-13)
Frappe Framework: v13.2.1 (version-13)

### PR DESCRIPTION
**Pull request by vamagithub**
closes #27419

Upon creating a new Purchase Order, or a Purchase Invoice, an error pops up indicating that the field "company_address" is not found

This is happening because doctypes like Purchase Order/ PINV doesn't have field "company_address".
After adding a "if" condition before setting the value will solve the issue.

### CODE REVIEW

File: erpnext/public/js/controllers/transaction.js [hunk 1]
```diff
@@ -864,7 +864,9 @@ erpnext.TransactionController = erpnext.taxes_and_totals.extend({
 						if (r.message) {
 							me.frm.set_value("billing_address", r.message);
 						} else {
-							me.frm.set_value("company_address", "");
+							if(frappe.meta.get_docfield(me.frm.doctype, 'company_address')){			
+								me.frm.set_value("company_address", "");
+							}
```
Comment (ankush) [inline erpnext/public/js/controllers/transaction.js]:
```suggestion
							if (frappe.meta.get_docfield(me.frm.doctype, 'company_address')){
								me.frm.set_value("company_address", "");
							}
```

formatting changes

File: erpnext/public/js/controllers/transaction.js [hunk 2]
```diff
@@ -864,7 +864,9 @@ erpnext.TransactionController = erpnext.taxes_and_totals.extend({
 						if (r.message) {
 							me.frm.set_value("billing_address", r.message);
 						} else {
-							me.frm.set_value("company_address", "");
+							if (frappe.meta.get_docfield(me.frm.doctype, 'company_address')){
```
Comment (ankush) [inline erpnext/public/js/controllers/transaction.js]:
```suggestion
							if (frappe.meta.get_docfield(me.frm.doctype, 'company_address')) {
```

**Review by ankush — APPROVED** [review]
