### PR TITLE
fix: Drop Shipping address based on customer shopping address

### LINKED ISSUE #44019: DropShip Address is not maintained from Sales Order to Purchase Order
### Information about bug

When dropshipping an order with all items marked as "Delivered by Supplier", after creating the Purchase Order from the Sales Order, the Shipping Address reverts back to the Company Address instead of being the Customer Shipping Address.

This issue breaks the whole idea of Drop Shipping on ERP Next. It started to appear after upgrading to latest version.

### Module

buying, selling

### Version

ERPNext: v15.40.0 (HEAD)
Frappe Framework: v15.46.0 (HEAD)
Frappe HR: v15.33.2 (HEAD)
Frappe Insights: v2.2.6 (HEAD)
Raven: v2.0.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by Nihantra-Patel**
Version 15 & 14

fixes: https://github.com/frappe/erpnext/issues/44019 & https://github.com/frappe/erpnext/issues/37892

___

**Before:**

- For Drop shipping, if the purchase order is made with the default supplier, the flow works properly. However, when creating a purchase order without the default supplier, it redirects to the purchase page and sets the company address, but it should set the customer's shipping address instead of the company address.

[Before_DropShipping.webm](https://github.com/user-attachments/assets/bb53dc19-4465-400f-ba02-a3d67fd8d28a)

<br>

**After:**

- Set the value in the `set_missing_values` because some details were not being fetched. Also, fixed the condition in `transaction.js`. Previously, when redirecting from the sales order to the purchase order, the refresh event would trigger, removing the customer address and setting the company address. Now, I’ve added the `is_drop_ship` condition. If `is_drop_ship` is true, the refresh event won’t trigger, and the customer address will be kept.

[After_DropShipping.webm](https://github.com/user-attachments/assets/7c57ad7f-a658-41fd-aa6b-849ecbeeacc4)

### CODE REVIEW

File: erpnext/public/js/controllers/transaction.js [hunk 1]
```diff
@@ -956,9 +956,14 @@ erpnext.TransactionController = class TransactionController extends erpnext.taxe
 
 		if (frappe.meta.get_docfield(this.frm.doctype, "shipping_address") &&
 			['Purchase Order', 'Purchase Receipt', 'Purchase Invoice'].includes(this.frm.doctype)) {
-			erpnext.utils.get_shipping_address(this.frm, function() {
-				set_party_account(set_pricing);
-			});
+				let is_drop_ship = me.frm.doc.items.some(item => item.delivered_by_supplier);
+
+				if (!is_drop_ship) {
+					console.log('get_shipping_address');
```
Comment (ruthra-kumar) [inline erpnext/public/js/controllers/transaction.js:962]: @Nihantra-Patel 

Can you remove this.
