### PR TITLE
fix: Table row in dialog should not have delete row option

### LINKED ISSUE #53442: Table row selection in dialog should not have delete row/duplicate row for specific use-cases
While creating a "Request for Raw Materials" from SO: 
- A dialog asks the user to choose the relevant selection from child table
- As soon as the user selects a selection -- he is shown "Delete row" & "Duplicate Row" button.
- This leads to confusion. 

Note: This issue is present almost everywhere, where dialog is asking for a selection. 
This is a bigger framework level problem since the dialog asks to make a selection from a "table" field, which when selected makes those 2 buttons visible -- we need to figure out how to hide those buttons for selected use-cases. 

Image

### PR DESCRIPTION
**Pull request by nishkagosalia**
fixes: https://github.com/frappe/erpnext/issues/53442

### CODE REVIEW

File: erpnext/selling/doctype/sales_order/sales_order.js [hunk 1]
```diff
@@ -1399,7 +1402,7 @@ erpnext.selling.SalesOrderController = class SalesOrderController extends erpnex
 			{
 				fieldtype: "Table",
 				fieldname: "items",
-				description: __("Select BOM, Qty and For Warehouse"),
+				cannot_delete_rows: true,
```
Comment (mihir-kandoi) [inline erpnext/selling/doctype/sales_order/sales_order.js:1404]: I think user should not be able to add a row either? @DipenFrappe

File: erpnext/selling/doctype/sales_order/sales_order.js [hunk 2]
```diff
@@ -1389,6 +1389,9 @@ erpnext.selling.SalesOrderController = class SalesOrderController extends erpnex
 
 	make_raw_material_request_dialog(r) {
 		var me = this;
+		r.message.forEach((item) => {
+			item.__checked = 1;
+		});
```
Comment (mihir-kandoi) [inline erpnext/selling/doctype/sales_order/sales_order.js]:
```suggestion
		r.message.forEach(item => item.__checked = 1);
```
